[server]
maxUploadSize = 2000  # Sets limit to 2GB (2000 MB)
enableCORS = false

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"